Repository MapChillE/uble-be, pull requests merged in 2025-07, with the labels that each got.

#2 [Feat] entity 생성
  src/main/java/com/ureca/uble/entity/BaseEntity.java
  src/main/java/com/ureca/uble/entity/Bookmark.java
  src/main/java/com/ureca/uble/entity/Brand.java
  src/main/java/com/ureca/uble/entity/Feedback.java
  src/main/java/com/ureca/uble/entity/Pin.java
  src/main/java/com/ureca/uble/entity/Store.java
  src/main/java/com/ureca/uble/entity/Token.java
  src/main/java/com/ureca/uble/entity/UsageHistory.java
  src/main/java/com/ureca/uble/entity/User.java
  src/main/java/com/ureca/uble/entity/enums/Category.java
  src/main/java/com/ureca/uble/entity/enums/Provider.java
  src/main/java/com/ureca/uble/entity/enums/Rank.java
  src/main/java/com/ureca/uble/entity/enums/Role.java
  src/main/java/com/ureca/uble/entity/enums/Season.java
Labels: feat

#18 [Feat] 즐겨찾기 API 구현
  src/main/java/com/ureca/uble/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/ureca/uble/domain/bookmark/dto/response/CreateBookmarkRes.java
  src/main/java/com/ureca/uble/domain/bookmark/dto/response/DeleteBookmarkRes.java
  src/main/java/com/ureca/uble/domain/bookmark/dto/response/GetBookmarkRes.java
  src/main/java/com/ureca/uble/domain/bookmark/exception/BookmarkErrorCode.java
  src/main/java/com/ureca/uble/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/ureca/uble/domain/bookmark/repository/CustomBookmarkRepository.java
  src/main/java/com/ureca/uble/domain/bookmark/repository/CustomBookmarkRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/bookmark/service/BookmarkService.java
  src/main/java/com/ureca/uble/domain/usageHistory/controller/UsageHistoryController.java
  src/main/java/com/ureca/uble/domain/usageHistory/repository/CustomUsageHistoryRepository.java
  src/main/java/com/ureca/uble/domain/usageHistory/repository/CustomUsageHistoryRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/usageHistory/service/UsageHistoryService.java
  src/main/java/com/ureca/uble/entity/Bookmark.java
  src/main/java/com/ureca/uble/entity/Brand.java
  src/main/java/com/ureca/uble/global/response/CursorPageRes.java
  src/test/java/com/ureca/uble/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/ureca/uble/domain/usageHistory/service/UsageHistoryServiceTest.java
Labels: test, refactor, feat

#20 [Feat] 이용 내역 등록 구현
  src/main/java/com/ureca/uble/domain/brand/exception/BrandErrorCode.java
  src/main/java/com/ureca/uble/domain/brand/repository/BenefitRepository.java
  src/main/java/com/ureca/uble/domain/store/exception/StoreErrorCode.java
  src/main/java/com/ureca/uble/domain/store/repository/StoreRepository.java
  src/main/java/com/ureca/uble/domain/usageHistory/controller/UsageHistoryController.java
  src/main/java/com/ureca/uble/domain/usageHistory/service/UsageHistoryService.java
  src/main/java/com/ureca/uble/domain/users/controller/UsageHistoryController.java
  src/main/java/com/ureca/uble/domain/users/dto/request/CreateUsageHistoryReq.java
  src/main/java/com/ureca/uble/domain/users/dto/response/CreateUsageHistoryRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/UsageHistoryRes.java
  src/main/java/com/ureca/uble/domain/users/exception/UserErrorCode.java
  src/main/java/com/ureca/uble/domain/users/repository/CustomUsageHistoryRepository.java
  src/main/java/com/ureca/uble/domain/users/repository/CustomUsageHistoryRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/users/repository/UsageCountRepository.java
  src/main/java/com/ureca/uble/domain/users/repository/UsageHistoryRepository.java
  src/main/java/com/ureca/uble/domain/users/service/UsageHistoryService.java
  src/main/java/com/ureca/uble/entity/UsageCount.java
  src/main/java/com/ureca/uble/entity/UsageHistory.java
  src/main/java/com/ureca/uble/entity/User.java
  src/main/java/com/ureca/uble/entity/enums/BenefitType.java
  src/test/java/com/ureca/uble/domain/usageHistory/service/UsageHistoryServiceTest.java
Labels: test, feat, rename

#28 [Feat] 혜택 사용 가능 여부 초기화 스케줄러 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/ureca/uble/UbleApplication.java
  src/main/java/com/ureca/uble/domain/brand/repository/BenefitRepository.java
  src/main/java/com/ureca/uble/domain/store/controller/StoreController.java
  src/main/java/com/ureca/uble/domain/users/repository/UsageCountRepository.java
  src/main/java/com/ureca/uble/global/config/BatchConfig.java
  src/main/java/com/ureca/uble/global/config/RedisConfig.java
  src/main/java/com/ureca/uble/global/schedule/UsageScheduler.java
  src/main/java/com/ureca/uble/global/schedule/batch/LocalBatchConfig.java
  src/main/java/com/ureca/uble/global/schedule/batch/NormalBatchConfig.java
  src/main/java/com/ureca/uble/global/schedule/batch/UsageBatchRunner.java
  src/main/java/com/ureca/uble/global/schedule/batch/VipBatchConfig.java
  src/main/java/com/ureca/uble/global/schedule/util/RedisLockUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat

#33 [Fix] 스케줄러 최종 수정
  src/main/java/com/ureca/uble/global/schedule/UsageScheduler.java
  src/main/java/com/ureca/uble/global/schedule/batch/NormalBatchConfig.java
Labels: fix

#37 [Fix] 이용 내역 등록 로직 수정
  src/main/java/com/ureca/uble/domain/store/repository/CustomStoreRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomStoreRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/users/service/UsageHistoryService.java
  src/test/java/com/ureca/uble/domain/users/service/UsageHistoryServiceTest.java
Labels: fix, test

#39 [Fix] 전체 매장 리스트 조회 수정
  src/main/java/com/ureca/uble/domain/store/controller/StoreController.java
  src/main/java/com/ureca/uble/domain/store/dto/response/GetStoreRes.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomStoreRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomStoreRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
  src/test/java/com/ureca/uble/domain/store/service/StoreServiceTest.java
Labels: fix

#43 [Feat] 매장 상세 조회 API 구현
  src/main/java/com/ureca/uble/domain/brand/repository/BenefitRepository.java
  src/main/java/com/ureca/uble/domain/store/controller/StoreController.java
  src/main/java/com/ureca/uble/domain/store/dto/response/GetBenefitInfoRes.java
  src/main/java/com/ureca/uble/domain/store/dto/response/GetStoreDetailRes.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomStoreRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomStoreRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/store/repository/StoreRepository.java
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
  src/main/java/com/ureca/uble/domain/users/service/UsageHistoryService.java
  src/main/java/com/ureca/uble/entity/enums/Rank.java
  src/test/java/com/ureca/uble/domain/store/service/StoreServiceTest.java
  src/test/java/com/ureca/uble/domain/users/service/UsageHistoryServiceTest.java
Labels: fix, test, feat

#42 [UBLE-26] feat: 피드백 생성 API 구현
  src/main/java/com/ureca/uble/domain/feedback/controller/FeedbackController.java
  src/main/java/com/ureca/uble/domain/feedback/dto/request/CreateFeedbackReq.java
  src/main/java/com/ureca/uble/domain/feedback/dto/response/CreateFeedbackRes.java
  src/main/java/com/ureca/uble/domain/feedback/service/FeedbackService.java
  src/main/java/com/ureca/uble/entity/Feedback.java
  src/test/java/com/ureca/uble/domain/feedback/FeedbackServiceTest.java
Labels: feat, BE

#49 [Fix] exposedHeaders 설정 및 cors 설정
  src/main/java/com/ureca/uble/global/config/SecurityConfig.java
Labels: fix, BE

#57 fix: swagger https 설정
  src/main/java/com/ureca/uble/global/config/SecurityConfig.java
  src/main/java/com/ureca/uble/global/config/SwaggerConfig.java
Labels: fix, BE

#58 [Fix] SecurityConfig 수정
  src/main/java/com/ureca/uble/global/config/SecurityConfig.java
Labels: fix, BE

#62 [Fix] 제휴처 검색 수정
  src/main/java/com/ureca/uble/domain/brand/repository/BrandNoriDocumentRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandNoriRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandNoriRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/brand/service/BrandService.java
  src/main/java/com/ureca/uble/domain/common/service/CommonService.java
  src/main/resources/elasticsearch/brand-nori-settings.json
Labels: fix, refactor

#63 [Feat] 로그 추가 기능 구현
  src/main/java/com/ureca/uble/domain/brand/repository/BenefitRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/BrandClickLogDocumentRepository.java
  src/main/java/com/ureca/uble/domain/brand/service/BrandService.java
  src/main/java/com/ureca/uble/domain/common/controller/CommonController.java
  src/main/java/com/ureca/uble/domain/common/dto/request/CreateSearchLogReq.java
  src/main/java/com/ureca/uble/domain/common/dto/response/CreateSearchLogRes.java
  src/main/java/com/ureca/uble/domain/common/service/CommonService.java
  src/main/java/com/ureca/uble/domain/store/repository/SearchLogDocumentRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/StoreClickLogDocumentRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/StoreRepository.java
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
  src/main/java/com/ureca/uble/domain/users/dto/response/CreateUsageHistoryRes.java
  src/main/java/com/ureca/uble/domain/users/repository/UsageHistoryDocumentRepository.java
  src/main/java/com/ureca/uble/domain/users/service/UsageHistoryService.java
  src/main/java/com/ureca/uble/entity/Brand.java
  src/main/java/com/ureca/uble/entity/document/BrandClickLogDocument.java
  src/main/java/com/ureca/uble/entity/document/SearchLogDocument.java
  src/main/java/com/ureca/uble/entity/document/StoreClickLogDocument.java
  src/main/java/com/ureca/uble/entity/document/UsageHistoryDocument.java
  src/main/java/com/ureca/uble/entity/enums/SearchType.java
  src/main/java/com/ureca/uble/global/config/WebClientConfig.java
  src/main/java/com/ureca/uble/global/schedule/LogBackupScheduler.java
  src/main/resources/application.yml
  src/main/resources/elasticsearch/search-log-settings.json
  src/test/java/com/ureca/uble/domain/brand/service/BrandServiceTest.java
  src/test/java/com/ureca/uble/domain/store/service/StoreServiceTest.java
  src/test/java/com/ureca/uble/domain/users/service/UsageHistoryServiceTest.java
Labels: docs, feat

#64 [Fix] 사용자 정보 관련 API들에 바코드 번호 추가
  src/main/java/com/ureca/uble/domain/users/dto/request/UpdateUserInfoReq.java
  src/main/java/com/ureca/uble/domain/users/dto/response/GetUserInfoRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/UpdateUserInfoRes.java
  src/main/java/com/ureca/uble/domain/users/service/UserService.java
  src/main/java/com/ureca/uble/entity/User.java
  src/test/java/com/ureca/uble/domain/users/service/UserServiceTest.java
Labels: fix, test

#67 [Feat] 제휴처 자동완성 기능 구현
  src/main/java/com/ureca/uble/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uble/domain/brand/dto/response/BrandSuggestionListRes.java
  src/main/java/com/ureca/uble/domain/brand/dto/response/SuggestionRes.java
  src/main/java/com/ureca/uble/domain/brand/exception/BrandErrorCode.java
  src/main/java/com/ureca/uble/domain/brand/repository/BrandNgramDocumentRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/BrandSuggestionDocumentRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandNoriRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandSuggestionDocumentRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandSuggestionDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/brand/service/BrandService.java
  src/main/java/com/ureca/uble/domain/category/repository/CategoryNgramDocumentRepository.java
  src/main/java/com/ureca/uble/domain/category/repository/CategorySuggestionDocumentRepository.java
  src/main/java/com/ureca/uble/domain/category/repository/CustomCategorySuggestionDocumentRepository.java
  src/main/java/com/ureca/uble/domain/category/repository/CustomCategorySuggestionDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/common/service/CommonService.java
  src/main/java/com/ureca/uble/domain/store/repository/StoreNgramDocumentRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/StoreSuggestionDocumentRepository.java
  src/main/java/com/ureca/uble/entity/document/BrandNgramDocument.java
  src/main/java/com/ureca/uble/entity/document/BrandSuggestionDocument.java
  src/main/java/com/ureca/uble/entity/document/CategorySuggestionDocument.java
  src/main/java/com/ureca/uble/entity/document/StoreSuggestionDocument.java
  src/main/java/com/ureca/uble/entity/enums/SuggestionType.java
  src/main/java/com/ureca/uble/global/exception/GlobalErrorCode.java
  src/main/resources/elasticsearch/brand-ngram-settings.json
  src/main/resources/elasticsearch/brand-suggestion-settings.json
  src/main/resources/elasticsearch/category-suggestion-settings.json
  src/main/resources/elasticsearch/store-ngram-settings.json
  src/main/resources/elasticsearch/store-suggestion-settings.json
Labels: chore, feat, rename

#71 [Docs] application_yml 개발/배포 버전 분리
  .github/workflows/cd-dev.yml
Labels: docs, BE

#72 [Docs] application_yml 개발/배포 버전 분리
  .github/workflows/cd-release.yml
Labels: docs, BE

#76 [Feat] 사용자 개인 통계 조회 API 구현
  src/main/java/com/ureca/uble/domain/brand/repository/BrandClickLogDocumentRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandClickLogDocumentRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandClickLogDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/users/controller/UserController.java
  src/main/java/com/ureca/uble/domain/users/dto/response/BenefitUsageComparisonRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/BenefitUsagePatternRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/BrandRankRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/CategoryRankRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/GetUserStatisticsRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/MonthlyBenefitUsageRes.java
  src/main/java/com/ureca/uble/domain/users/repository/CustomUsageHistoryDocumentRepository.java
  src/main/java/com/ureca/uble/domain/users/repository/CustomUsageHistoryDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/users/repository/UsageHistoryDocumentRepository.java
  src/main/java/com/ureca/uble/domain/users/service/UserService.java
  src/main/resources/application.yml
Labels: feat, BE

#89 [Feat] 자주가는 곳 저장/조회/삭제 구현
  src/main/java/com/ureca/uble/domain/auth/service/AuthService.java
  src/main/java/com/ureca/uble/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uble/domain/brand/dto/response/CategoryRes.java
  src/main/java/com/ureca/uble/domain/brand/dto/response/InitialDataRes.java
  src/main/java/com/ureca/uble/domain/brand/service/BrandService.java
  src/main/java/com/ureca/uble/domain/category/repository/CategoryRepository.java
  src/main/java/com/ureca/uble/domain/pin/controller/PinController.java
  src/main/java/com/ureca/uble/domain/pin/dto/request/CreatePinReq.java
  src/main/java/com/ureca/uble/domain/pin/dto/response/CreatePinRes.java
  src/main/java/com/ureca/uble/domain/pin/dto/response/DeletePinRes.java
  src/main/java/com/ureca/uble/domain/pin/dto/response/GetPinDetailRes.java
  src/main/java/com/ureca/uble/domain/pin/dto/response/GetPinRes.java
  src/main/java/com/ureca/uble/domain/pin/exception/PinErrorCode.java
  src/main/java/com/ureca/uble/domain/pin/repository/PinRepository.java
  src/main/java/com/ureca/uble/domain/pin/service/PinService.java
  src/main/java/com/ureca/uble/entity/Pin.java
  src/test/java/com/ureca/uble/domain/auth/service/AuthServiceTest.java
  src/test/java/com/ureca/uble/domain/brand/service/BrandServiceTest.java
  src/test/java/com/ureca/uble/domain/pin/service/PinServiceTest.java
Labels: test, feat, BE

#91 [Feat] 어드민 통계 기능 구현
  src/main/java/com/ureca/uble/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/GetClickRankListRes.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/GetLocalRankListRes.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/GetUsageRankListRes.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/RankDetailRes.java
  src/main/java/com/ureca/uble/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandClickLogDocumentRepository.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandClickLogDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/common/util/SearchFilterUtils.java
  src/main/java/com/ureca/uble/domain/users/repository/CustomUsageHistoryDocumentRepository.java
  src/main/java/com/ureca/uble/domain/users/repository/CustomUsageHistoryDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/entity/document/UsageHistoryDocument.java
  src/main/java/com/ureca/uble/entity/enums/RankTarget.java
  src/test/java/com/ureca/uble/domain/users/service/UsageHistoryServiceTest.java
Labels: chore, feat, BE

#95 [Feat] 통계 기반 추천 API 구현
  src/main/java/com/ureca/uble/domain/brand/repository/BrandRepository.java
  src/main/java/com/ureca/uble/domain/users/controller/UserController.java
  src/main/java/com/ureca/uble/domain/users/dto/response/GetRecommendationRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/GetSimilarUserRecommendationListRes.java
  src/main/java/com/ureca/uble/domain/users/dto/response/GetTimeRecommendationListRes.java
  src/main/java/com/ureca/uble/domain/users/exception/UserErrorCode.java
  src/main/java/com/ureca/uble/domain/users/repository/CustomUsageHistoryDocumentRepository.java
  src/main/java/com/ureca/uble/domain/users/repository/CustomUsageHistoryDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/users/service/UserService.java
  src/main/java/com/ureca/uble/entity/document/UsageHistoryDocument.java
Labels: chore, feat, BE

#104 [Fix] 매장 상세 조회 즐겨찾기 오류 수정
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
  src/test/java/com/ureca/uble/domain/store/service/StoreServiceTest.java
Labels: fix, BE

#108 [Fix] 통계 추천 반환 DTO 수정
  src/main/java/com/ureca/uble/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/ureca/uble/domain/users/dto/response/GetRecommendationRes.java
  src/main/java/com/ureca/uble/domain/users/service/UserService.java
Labels: fix, BE

#114 [Fix] validation 추가
  src/main/java/com/ureca/uble/domain/auth/controller/AuthController.java
  src/main/java/com/ureca/uble/domain/auth/dto/request/KakaoLoginReq.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandNoriRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/brand/repository/CustomBrandSuggestionDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/brand/service/BrandService.java
  src/main/java/com/ureca/uble/domain/category/repository/CustomCategorySuggestionDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/common/controller/CommonController.java
  src/main/java/com/ureca/uble/domain/common/dto/request/CreateSearchLogReq.java
  src/main/java/com/ureca/uble/domain/common/dto/response/CommonResponse.java
  src/main/java/com/ureca/uble/domain/common/exception/CommonErrorCode.java
  src/main/java/com/ureca/uble/domain/feedback/controller/FeedbackController.java
  src/main/java/com/ureca/uble/domain/feedback/dto/request/CreateFeedbackReq.java
  src/main/java/com/ureca/uble/domain/pin/controller/PinController.java
  src/main/java/com/ureca/uble/domain/pin/dto/request/CreatePinReq.java
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
  src/main/java/com/ureca/uble/domain/users/controller/UserController.java
  src/main/java/com/ureca/uble/domain/users/dto/request/UpdateUserInfoReq.java
  src/main/java/com/ureca/uble/global/exception/GlobalErrorCode.java
  src/main/java/com/ureca/uble/global/exception/GlobalExceptionHandler.java
Labels: fix, BE

#117 [Feat] 어드민 통계 조회 API 구현
  src/main/java/com/ureca/uble/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/GetDailySearchRankListRes.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/GetEmptySearchRankListRes.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/GetInterestChangeRes.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/GetInterestListRes.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/GetRankListRes.java
  src/main/java/com/ureca/uble/domain/admin/dto/response/InterestDetailRes.java
  src/main/java/com/ureca/uble/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uble/domain/common/repository/CustomSuggestionRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomSearchLogDocumentRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomSearchLogDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/store/repository/SearchLogDocumentRepository.java
  src/main/java/com/ureca/uble/entity/enums/InterestType.java
Labels: feat, BE

#119 [Fix] 자동완성 DTO 필드 수정
  src/main/java/com/ureca/uble/domain/store/dto/response/GetGlobalSuggestionRes.java
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
  src/main/java/com/ureca/uble/entity/document/StoreSuggestionDocument.java
Labels: fix, BE

#124 [Fix] 제휴처 전체 조회 API 북마크여부 조회 로직 수정
  src/main/java/com/ureca/uble/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uble/domain/brand/dto/response/BrandListRes.java
  src/main/java/com/ureca/uble/domain/brand/service/BrandService.java
  src/test/java/com/ureca/uble/domain/brand/service/BrandServiceTest.java
Labels: fix, test

#127 [Fix] 지도 자동완성 DTO 수정
  src/main/java/com/ureca/uble/domain/common/repository/CustomSuggestionRepository.java
  src/main/java/com/ureca/uble/domain/store/dto/response/GetGlobalSuggestionRes.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomLocationCoordinationDocumentRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomLocationCoordinationDocumentRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/store/repository/LocationCoordinationDocumentRepository.java
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
  src/main/java/com/ureca/uble/entity/document/StoreSuggestionDocument.java
Labels: fix, BE

#126 [Fix] 클러스터 대표 매장 조회 기능 추가
  src/main/java/com/ureca/uble/domain/store/controller/StoreController.java
  src/main/java/com/ureca/uble/domain/store/dto/response/GetStoreListRes.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomStoreRepository.java
  src/main/java/com/ureca/uble/domain/store/repository/CustomStoreRepositoryImpl.java
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
  src/main/java/com/ureca/uble/entity/Store.java
  src/test/java/com/ureca/uble/domain/store/service/StoreServiceTest.java
Labels: fix, test, BE

#134 [Chore] 배포 서버 CD script 수정
  .github/workflows/cd-release.yml
Labels: chore

#140 [Fix] 줌 레벨 수정
  src/main/java/com/ureca/uble/domain/store/service/StoreService.java
Labels: fix

#141 [Fix] 바코드 번호 검증 수정
  .gitignore
  src/main/java/com/ureca/uble/domain/users/dto/request/UpdateUserInfoReq.java
  src/main/java/com/ureca/uble/global/logging/LoggingFilter.java
Labels: fix

#145 [Fix] traceId 헤더에 추가
  src/main/java/com/ureca/uble/domain/users/service/UserService.java
Labels: fix, BE
